import Markdoc from "@markdoc/markdoc";
import * as React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import css from "../build/site.css" with { type: "text" };
import { components, SiteIndex } from "./components";
import { PageContext, type PageInfo } from "./context";
import { Layout } from "./layout";
import { config } from "./schema";
import { astText, listPages, loadSite } from "./site";

const MARKER = ".mdnet-site";

function main(args: string[]): number {
  const [input, output] = args;
  if (!input || !output) {
    console.error("usage: render <markdown-docs-root> <html-output-dir>");
    return 2;
  }

  const root = resolve(input);
  const out = resolve(output);
  prepareOutput(out);

  const site = loadSite(root);
  const pages = listPages(root);
  let warnings = 0;

  for (const path of pages) {
    const source = readFileSync(join(root, path), "utf8");
    const ast = Markdoc.parse(source);
    for (const error of Markdoc.validate(ast, config)) {
      if (error.error.level === "error" || error.error.level === "critical") {
        warnings++;
        console.error(`${path}:${(error.lines[0] ?? 0) + 1}: ${error.error.message}`);
      }
    }

    const pkg = site.packages.find((p) => path.startsWith(`${p.id}/`));
    const info: PageInfo = { path, site, pkg };
    const h1 = ast.children.find((c) => c.type === "heading" && c.attributes.level === 1);
    const title = h1 ? astText(h1) : (pkg?.id ?? "API documentation");
    const sections = ast.children.filter((c) => c.type === "heading" && c.attributes.level === 2).map(astText);
    const declaration = ast.children.find((c) => c.type === "fence");
    const namespace = /^namespace\s+([\w.]+);/m.exec(String(declaration?.attributes.content ?? ""))?.[1];

    // The root index is rendered from site data (package metadata); its Markdown stays a plain list for agents.
    const content = path === "index.md" ? <SiteIndex /> : Markdoc.renderers.react(Markdoc.transform(ast, config), React, { components });
    const html =
      "<!doctype html>" +
      renderToStaticMarkup(
        <PageContext.Provider value={info}>
          <Layout title={title} namespace={namespace} sections={sections}>
            {content}
          </Layout>
        </PageContext.Provider>,
      );

    const target = join(out, path.replace(/\.md$/, ".html"));
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, html);
    // The Markdown source sits next to each page so agents can fetch it from the published site.
    copyFileSync(join(root, path), join(out, path));
  }

  for (const pkg of site.packages) {
    // A published site is also a valid `mdnet download` source. Package folders are named by id.
    mkdirSync(join(out, pkg.id), { recursive: true });
    copyFileSync(join(root, pkg.id, "mdnet.json"), join(out, pkg.id, "mdnet.json"));
  }

  writeFileSync(join(out, "site.css"), css);
  if (existsSync(join(root, "index.md"))) copyFileSync(join(root, "index.md"), join(out, "llms.txt"));
  writeFileSync(join(out, ".nojekyll"), "");
  writeFileSync(join(out, MARKER), "Generated by mdnet. This folder is replaced on every render.\n");

  console.log(`Rendered ${pages.length} page(s) to ${out}`);
  return warnings > 0 ? 1 : 0;
}

/** Output folders are recreated, but only when they are empty or were produced by mdnet. */
function prepareOutput(out: string) {
  if (existsSync(out)) {
    const entries = readdirSync(out);
    if (entries.length > 0 && !entries.includes(MARKER)) {
      throw new Error(`${out} is not empty and was not generated by mdnet; refusing to overwrite it.`);
    }
    // Clear contents rather than the folder itself: on Windows a served or open folder cannot be removed.
    for (const entry of entries) rmSync(join(out, entry), { recursive: true, force: true });
  }
  mkdirSync(out, { recursive: true });
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
